### ISSUE TITLE
document ready & foundation

### ISSUE THREAD

**Issue by fyyyyy** [lhorie/mithril#24]
I am trying to reinitialize foundation after mithril added new dom, specifically tabs.
Mithril docs say it will render before document ready but it appears not to ?
Thats why foundation wont find any tabs on document ready.

From the foundation docs

>Adding New Tab Content After Page Load
If you add new content after the page has been loaded, you will need to reinitialize the Foundation JavaScript by running the following:
$(document).foundation(); // `im running this in $(document).ready`

**Comment by fyyyyy** [comment]
![debugger](https://cloud.githubusercontent.com/assets/3744048/6212206/bac828ee-b5e2-11e4-9bbb-b5a6a676af89.png)

**Comment by derekbreden** [comment]
This is the stable repo, not the development repo --- Sticky Issue #12 recommends not posting here.

No one monitors this I think is the main concern mentioned there.

I am not too sure, but maybe you want to put your `$(document).foundation` in the config function of mithril, "Accessing the real DOM element" in the mithril docs. (your code would maybe go after the `isInitialized` check there.)

http://lhorie.github.io/mithril/mithril.html
![screenshot 2015-04-22 20 52 50](https://cloud.githubusercontent.com/assets/8616734/7290338/f0a04d8e-e931-11e4-86a0-d0c8b72d7cf8.png)
http://lhorie.github.io/mithril/mithril.html#accessing-the-real-dom-element
![screenshot 2015-04-22 20 53 41](https://cloud.githubusercontent.com/assets/8616734/7290339/f0b7a77c-e931-11e4-906b-6698a870e61d.png)

**Comment by fyyyyy** [comment]
thx :+1:
