### ISSUE TITLE
Mithril site improvements

### ISSUE THREAD

**Issue by dannyvankooten** [lhorie/mithril#47]
Hey @lhorie,

While browsing the Mithril site, I couldn't help but notice the date in the footer being stuck at 2014 and also seeing only tweets from 2014-2015. I really think in terms of "marketing" the Mithril project, a few simple improvements to the site could go a long way.

I'd love to pick this one up, but wanted to hear your thoughts on it before I get cracking. Here's what I'd like to do.
- Use Jekyll for the entire site so it becomes a tad easier to manage. `/archive/` can stay pure HTML.
- Hand-picking a few more recent tweets.
- Some styling improvements. More whitespace and less gray mostly. 

Give me the signal and I'll start submitting PR's. Thank you. :)

**Comment by tivac** [comment]
See #12, sorry for the lack of response!
