### ISSUE TITLE
Documentation vnode.state.data special or wrong?

### ISSUE THREAD

**Issue by waldhol** [lhorie/mithril#53]
In the 1.0 documentation of components in chapter "State" the example reads:
```javascript
var ComponentWithInitialState = {
    data: "Initial content",
    view: function(vnode) {
        return m("div", vnode.state.data)
    }
}
```
Shouldn't this be `vnode.attr.data` at this point?
The copy from `attr` to `state` is shown in the next example.

**Comment by tivac** [comment]
See #12 please.
