### ISSUE TITLE
1.0.1 tag is missing, used with bower

### ISSUE THREAD

**Issue by simov** [lhorie/mithril#59]

**Comment by tivac** [comment]
Wrong repo (yes it's confusing).

You want https://github.com/lhorie/mithril.js/

**Comment by simov** [comment]
Tried it, but I'm getting the following error:
```
bower mithril.js#1.0.0       ENOTFOUND Package mithril.js not found
```

**Comment by tivac** [comment]
Mithril doesn't publish a bower package any more AFAIK. That might be part of the issue? Please open an issue on the `mithril.js` repo.
